# Generated by Django 6.0.3 on 2026-03-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id_peca', models.AutoField(primary_key=True, serialize=False)),
                ('nome_da_peca', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_estimado', models.DurationField(help_text='Tempo estimado (HH:MM:SS)')),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id_moto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='oficina.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='oficina.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='oficina.moto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDaOrdem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_item', models.CharField(choices=[('peca', 'Peça'), ('servico', 'Serviço')], max_length=10)),
                ('id_referencia', models.IntegerField()),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='oficina.ordemservico')),
            ],
        ),
    ]
